### ISSUE TITLE
TV doesn't show

### ISSUE THREAD

**Issue by kevinchristianson** [PickFlicks/App#14]
[TVFragment](https://github.com/PickFlicks/App/blob/master/app/src/main/java/com/pickflix/app/fragments/TVFragment.java) shares most of its code with [MovieFragment](https://github.com/PickFlicks/App/blob/master/app/src/main/java/com/pickflix/app/fragments/MovieFragment.java) (both inherit from [MediaFragment](https://github.com/PickFlicks/App/blob/master/app/src/main/java/com/pickflix/app/fragments/MediaFragment.java)), and data loads correctly, but nothing is displayed on the screen. If TVFragment is set as the landing page, then MovieFragment does not load.

**Comment by kevinchristianson** [comment]
@ritvikkar could you please have some of your LinkedIn friends look at this since it's stumped us for a while?

**Comment by kevinchristianson** [comment]
Our best guess is that this problem is caused by the setOffscreenPageLimit(NUM_PAGES) method call for the viewpager or the setRetainInstance(true) for the adapters which are done in the [MainActivity ](https://github.com/PickFlicks/App/blob/master/app/src/main/java/com/pickflix/app/MainActivity.java)class.

**Comment by zsmoore** [comment]
Hey it's me @ritvikkar's LinkedIn friend.

I'll take a look at this issue in the next few days and see if i can find something / submit a PR  to help out!

**Comment by kevinchristianson** [comment]
@zsmoore Thank you so much! We've been stumped by this problem for a while so we really appreciate you working on it with us. Let me know if there's anything I can do to help.

**Comment by grahamearley** [comment]
Looks like the issue here is that you're passing the main activity's `FragmentManager` into the media fragment's pager (for both the TV and movie pages). You obtain this in the media fragment by calling [`getFragmentManager()`](https://developer.android.com/reference/android/support/v4/app/Fragment#getfragmentmanager). This fragment manager allows you to add fragments to the _activity_.

Since you're using nested fragments here (main activity has media fragments which contain fragments), you need to pass the _fragment_'s `FragmentManager` into the media fragment's pager, so you can add nested fragments. You can access a fragment's fragment manager by calling [`getChildFragmentManager()`](https://developer.android.com/reference/android/support/v4/app/Fragment#getchildfragmentmanager) in a fragment.

The only change you need to make here is in the first line of `MediaFragment`'s method `setUpPager()`. Instead of passing in `getFragmentManager()` to the `ScreenSlidePagerAdapter` constructor, you should pass in `getChildFragmentManager()`, like this:

```java
adapter = new ScreenSlidePagerAdapter(getChildFragmentManager());
```


***

That did the trick for me, but let me know if it doesn't work for you! Also, let me know if my explanation didn't make sense :)

**Comment by kevinchristianson** [comment]
Thank you so much, Graham! Your explanation makes sense, we just didn't know about childFragmentManager. So happy to finally have this resolved since it's been bugging us for so long!
